# Uncomment the lines below you want to change by removing the # in the beginning

#scheme('Bubbles Screenshots')
workspace('ios/bubbles.xcworkspace')
devices([
	#"iPhone 8",
	#"iPhone SE",
	"iPhone 11"
])
languages([
	"en-US"
])
configuration('Release')
erase_simulator(true)
reinstall_app(true)
output_directory('fastlane/metadata/ios/screenshots')
